version: "3.9"
services:
  db:
    image: postgres:15
    container_name: roado-db
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: password
      POSTGRES_DB: roado_db
    ports:
      - "5431:5432" # host:container
    networks:
      - roado-net

  backend:
    build: ./backend/demo
    container_name: raado-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/roado_db
      SPRING_DATASOURCE_USERNAME: guest
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - roado-net

networks:
  roado-net:
